-- comandos do homework

	
SELECT id_pais, nome FROM PAIS ORDER BY nome DESC
SELECT cep, logradouro FROM ENDERECO WHERE UPPER(logradouro) LIKE 'A%'
SELECT cep FROM ENDERECO WHERE cep LIKE '%0'
SELECT numero FROM ENDERECO WHERE numero BETWEEN 1 AND 100
SELECT nome, cep FROM ENDERECO WHERE UPPER(nome) LIKE 'RUA' ORDER BY cep DESC
SELECT COUNT(*) FROM ENDERECO 
SELECT id_cidade, COUNT(id_cidade) FROM ENDERECO GROUP BY id_cidade


-- Feito em aula
CREATE TABLE PAIS (
    id_pais INT NOT NULL,
    nome VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id_pais)
);

CREATE TABLE ESTADO (
	id_estado INT PRIMARY KEY NOT NULL,
	nome VARCHAR(50) NOT NULL,
	id_pais INT NOT NULL,
	CONSTRAINT FK_ID_PAIS FOREIGN KEY ( ID_PAIS ) REFERENCES PAIS( ID_PAIS )
);

CREATE TABLE CIDADE (
	id_cidade INT PRIMARY KEY NOT NULL,
	nome VARCHAR(50) NOT NULL,
	id_estado INT NOT NULL,
	CONSTRAINT FK_ID_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO(ID_ESTADO)
);


CREATE TABLE BAIRRO (
	id_bairro INT PRIMARY KEY NOT NULL,
	nome VARCHAR(50) NOT NULL,
	id_cidade INT NOT NULL,
	id_estado INT NOT NULL,
	CONSTRAINT FK_ID_CIDADE FOREIGN KEY ( ID_CIDADE ) REFERENCES CIDADE( ID_CIDADE ),
	CONSTRAINT FK_ID_BAIRRO_ESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE ENDERECO (
	id_endereco INT PRIMARY KEY NOT NULL,
	nome VARCHAR(50) NOT NULL,
	logradouro VARCHAR(50) NOT NULL,
	numero INT NOT NULL,
	complemento VARCHAR(50) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	id_bairro INT NOT NULL,
	id_cidade INT NOT NULL,
	CONSTRAINT FK_ID_BAIRRO FOREIGN KEY ( ID_BAIRRO ) REFERENCES BAIRRO(ID_BAIRRO),
	CONSTRAINT FK_ID_CIDADE_ENDERECO FOREIGN KEY ( ID_CIDADE ) REFERENCES CIDADE(ID_CIDADE)
);


DROP TABLE ESTUDANTE

DROP TABLE PAIS 
DROP TABLE CIDADE
DROP TABLE ENDERECO 
DROP TABLE BAIRRO
DROP TABLE ESTADO

DROP SEQUENCE seq_pais
DROP SEQUENCE seq_estado
DROP SEQUENCE seq_cidade
DROP SEQUENCE seq_bairro
DROP SEQUENCE seq_endereco

CREATE SEQUENCE seq_pais
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_estado
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_cidade
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE seq_endereco
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE seq_bairro
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 

INSERT INTO PAIS
(ID_PAIS, NOME)
VALUES(SEQ_PAIS.nextval, 'Brasil');

INSERT INTO PAIS
(ID_PAIS, NOME)
VALUES(SEQ_PAIS.nextval, 'Argentina');

INSERT INTO ESTADO 
(ID_ESTADO, NOME, ID_PAIS)
VALUES(SEQ_ESTADO.nextval, 'Rio Grande do Sul',1);

INSERT INTO ESTADO
(ID_ESTADO, NOME, ID_PAIS)
VALUES(SEQ_ESTADO.nextval, 'Paraná',1);

INSERT INTO ESTADO
(ID_ESTADO, NOME, ID_PAIS)
VALUES(SEQ_ESTADO.nextval, 'Buenos Aires',2);

INSERT INTO ESTADO
(ID_ESTADO, NOME, ID_PAIS)
VALUES(SEQ_ESTADO.nextval, 'Entre Rios',2);

INSERT INTO CIDADE
(ID_CIDADE, NOME, ID_ESTADO)
VALUES(SEQ_CIDADE.nextval,'Porto Alegre',1);

INSERT INTO CIDADE
(ID_CIDADE, NOME, ID_ESTADO)
VALUES(SEQ_CIDADE.nextval,'Paraná',2);

INSERT INTO CIDADE
(ID_CIDADE, NOME, ID_ESTADO)
VALUES(SEQ_CIDADE.nextval,'Buenos Aires',3);

INSERT INTO CIDADE
(ID_CIDADE, NOME, ID_ESTADO)
VALUES(SEQ_CIDADE.nextval,'Paraná',4);

INSERT INTO BAIRRO
(ID_BAIRRO,NOME,ID_CIDADE,ID_ESTADO)
VALUES(SEQ_BAIRRO.nextval,'Petrópolis',1,1);

INSERT INTO BAIRRO
(ID_BAIRRO,NOME,ID_CIDADE,ID_ESTADO)
VALUES(SEQ_BAIRRO.nextval,'Laranjeiras',2,2);

INSERT INTO BAIRRO
(ID_BAIRRO,NOME,ID_CIDADE,ID_ESTADO)
VALUES(SEQ_BAIRRO.nextval,'Centro',3,3);

INSERT INTO BAIRRO
(ID_BAIRRO,NOME,ID_CIDADE,ID_ESTADO)
VALUES(SEQ_BAIRRO.nextval,'Bom Jesus',4,4);

INSERT INTO BAIRRO
(ID_BAIRRO,NOME,ID_CIDADE,ID_ESTADO)
VALUES(SEQ_BAIRRO.nextval,'Bairro Paraná',14,2);

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Avenida','Oswaldo Aranha',20,'Ap 100','80460-200',2,1);

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Rua','Andradas',200,'Ap 200','10460-300',2,1);
	

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Avenida','Lajeado',50,'Ap 200','20460-300',3,2);

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'AVENIDA','Nonoai',200,'Ap 150','30460-600',3,2);

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Rua','Milagres',200,'casa','70460-600',4,3);

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Rua','Ceará',1000,'casa','90460-600',4,3);
	

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Rua','Barbacena',99,'ap 300','80420-600',5,4);

INSERT INTO ENDERECO
(ID_ENDERECO,NOME,LOGRADOURO ,NUMERO, COMPLEMENTO,CEP,ID_BAIRRO,ID_CIDADE)
VALUES(SEQ_ENDERECO.nextval,'Rua','Lindoia',1000,'casa','80460-600',5,4);
	



